### ISSUE TITLE
google page insights

### ISSUE THREAD

**Issue by vtolstov** [mmrath/hugo-bootstrap#1]
google page insights says:
- move css on bottom or inline in html : css/theme/default.css , css/font-awesome.min.css , css/style.css , css/highlight/default.css

**Comment by mmrath** [comment]
@vtolstov Thanks for reporting this. Would you like to submit a PR for this?

**Comment by vtolstov** [comment]
I don't know how to fix this , i'm newbie with hugo =)

**Comment by mmrath** [comment]
I have updated this theme to latest bootstrap 4. I am closing this issue for now. Please open a new one if the latest theme does not do what you need.
