### ISSUE TITLE
theme rendring is complete via ‘hugo serve’ but incomplete via s3 hosting

### ISSUE THREAD

**Issue by dehylton** [mmrath/hugo-bootstrap#13]
Prior to posting this issue, I reached out to the hugo community (see [this](https://discourse.gohugo.io/t/bootstrap-theme-is-complete-via-hugo-serve-but-incomplete-via-s3-hosting/)) for assistance.

I have since tried several other themes and have not had the issue with them - so it appears as if the theme itself has a bug which does not show when used via "hugo serve" ... I have not yet found the cause, but wanted to go ahead and report.

**Comment by mmrath** [comment]
Any chance I can see a test/demo hosted on s3?
