### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by rabeloo** [mmrath/hugo-bootstrap#15]
I'm trying to update my blog, but when runs hugo command i received this error:

`Started building sites ...
ERROR 2017/09/09 01:20:28 Error while rendering "page": template: theme/page/single.html:12:3: executing "theme/page/single.html" at <partial "foot" .>: error calling partial: template: theme/partials/foot.html:1:9: executing "theme/partials/foot.html" at <partial "base/footer...>: error calling partial: template: theme/partials/base/footer.html:9:31: executing "theme/partials/base/footer.html" at <len .Site.Menus.foot...>: error calling len: len of untyped nil`

**Comment by mmrath** [comment]
@rabeloo I just pushed a commit. could you try?

**Comment by rabeloo** [comment]
Thanks @mmrath, was generated successfully!

Just to inform, I've been receiving a WARNING message below:

> Started building sites ...
> WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.
