### ISSUE TITLE
I really liked the old design

### ISSUE THREAD

**Issue by mightyBroccoli** [mmrath/hugo-bootstrap#17]
Can i reproduce the old design with these new features? 
The old one was straight forward and simple this colorful design is fancy but I liked the old one better :/

**Comment by mmrath** [comment]
Hi Nico, do you think you can fork and use your fork? I can create a branch with old design but I will not be able to maintain it.

**Comment by mightyBroccoli** [comment]
Maybe I am just a little old fashioned I started using this design because of the simplicity. I like the colors its  more that the tabs in the header are that far to the right. In the old design they were at the border of the textfield below. I liked that.
I hope that this description makes any sense to you :D

**Comment by mmrath** [comment]
Ok, I think I can change that in such a way that it is customisable. The
colors can also be customisable.

**Comment by mightyBroccoli** [comment]
Yes I found the default file to customize the color. I am not 100% happy with just 6 choices but never the less I like updating stuff :D 
I would love that :)

**Comment by mmrath** [comment]
You can have any class not just the ones bootstrap has.

**Comment by mightyBroccoli** [comment]
I need to take a look at this :) I am not that great with php thats why I am probably a little slow on this 🦄
