### ISSUE TITLE
It seems that brand and topline are not included in header?

### ISSUE THREAD

**Issue by shenwei356** [mmrath/hugo-bootstrap#2]
Hi, 

It seems that brand and topline are not included in header?

Why's that? Any consideration?

Wei

**Comment by jmhickman** [comment]
Yes, I also have this issue, any chance we could get a fix or a clarification on how to use these?

Also, my site's top bar is a grey instead of the black the screenshots show. Is this a parameter somewhere?

**Comment by shenwei356** [comment]
Change the theme in theme file:

```
hugo-bootstrap/layouts/partials/base/imports.html
```

or better way, create same directory in your site directory

```
/baseOfYourSite/layouts/partials/base/imports.html
```

And then change theme and highlight

```
  <link rel="stylesheet" href="{{ "/css/theme/" | absURL }}yeti.css">
```

```
  <link rel="stylesheet" href="{{ "/css/highlight/" | absURL }}yeti.css">
```

**Comment by philtgun** [comment]
Also there is easier way to do it, though it is not documented. You can just specify bootswatch theme in config file. Example for config.toml:
```
[params]
  [params.theme]
    name = "yeti"
```

**Comment by mmrath** [comment]
I have updated this theme to latest bootstrap 4. I am closing this issue for now. Please open a new one if the latest theme does not do what you need.

**Comment by mmrath** [comment]
Closing
