### ISSUE TITLE
Some code cause hang on of highlight.pack.js

### ISSUE THREAD

**Issue by shenwei356** [mmrath/hugo-bootstrap#4]
I tried to highlight text below, but it made the page hang on, and this was caused by `highlight.pack.js`:

```
BenchmarkCheckLetterWithMap 2000000000 0.20 ns/op
BenchmarkCheckLetterWithSlice 2000000000 0.01 ns/op
```

**Comment by mmrath** [comment]
I have updated this theme to latest bootstrap 4. I am closing this issue for now. Please open a new one if the latest theme does not do what you need.
