### ISSUE TITLE
Sidebar social links?

### ISSUE THREAD

**Issue by appernetic** [mmrath/hugo-bootstrap#5]
Hi,
what is the trick to make social links to show up in the sidebar?

**Comment by tutysara** [comment]
I have the same question too, couldn't find any thing, ended up modifying sidebar.html to add them in my local copy

**Comment by mmrath** [comment]
I have updated this theme to latest bootstrap 4. I am closing this issue for now. Please open a new one if the latest theme does not do what you need.
