### ISSUE TITLE
WARNING: Page's Now is deprecated and will be removed in a future release. Use now (the template func).

### ISSUE THREAD

**Issue by hippora** [mmrath/hugo-bootstrap#8]
WARNING: Page's Now is deprecated and will be removed in a future release. Use now (the template func).

**Comment by anthonyfok** [comment]
For reference, @mmrath fixed this issue in layouts/partials/base/footer.html on 14 Apr 2017 in commit 33dba4c20f1111399f495f2533c465c4402a6208 titled "Update to hugo 0.20".

(Google brought me here while I was researching for gohugoio/hugo#3629. :smile:)
